#!/bin/sh /etc/rc.common

START=19

USE_PROCD=1

start_service() {
        procd_open_instance mlx4_br
        procd_set_param command /usr/bin/mlx4_br
        procd_set_param respawn ${respawn_threshold:-3600} ${respawn_timeout:-5} ${respawn_retry:-5}
        procd_set_param limits core="unlimited"
        procd_set_param stdout 1
        procd_set_param stderr 1
        procd_set_param user root # run service as user root
        procd_set_param pidfile /var/run/mlx4_br.pid # write a pid file on instance start and remove it on stop
        procd_set_param term_timeout 60 # wait before sending SIGKILL
        procd_close_instance
}
